#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=bld.path.ant_glob('**/*.cpp'),
    target='kodocpp_tests',
    use=['kodocpp_includes', 'fifi_includes', 'sak_includes',
         'stub_includes', 'gtest', 'boost_includes', 'boost_system',
         'boost_filesystem','boost_iostreams', 'boost_program_options',
         'kodocpp'],
    shlib_path='../')
