#! /usr/bin/env python
# encoding: utf-8

# The search path is relevant for the shared library
search_path = []

# The kodo-c shared library will be copied to the same folder as the test
# binary when the test is executed by wurf_runner
if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

# First, we test with the kodo-c static library (to make debugging easier)
bld.program(
    features='cxx test',
    source=['kodocpp_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='kodocpp_static_tests',
    use=['kodocpp_static_includes', 'gtest'])

# Second, We test with the kodo-c shared library (which won't work on
# Android and iOS)
if bld.get_mkspec_platform() not in ['android', 'ios']:

    bld.program(
        features='cxx test',
        source=['kodocpp_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
        target='kodocpp_tests',
        rpath=search_path,
        use=['kodocpp_includes', 'gtest'])
