#! /usr/bin/env python
# encoding: utf-8

search_path = []

# The kodo-c shared library will be copied to the same folder as the test
# binary when the test is executed by wurf_runner
if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(
    features='cxx test',
    source=['kodocpp_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='../kodocpp_tests',
    rpath=search_path,
    use=['kodocpp_includes', 'gtest'])
