#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='is_symbol_pivot_counter.cpp',
            target='is_symbol_pivot_counter',
            use=['kodocpp_static_includes'])
