#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='cxx',
            source='is_symbol_pivot_counter.cpp',
            target='is_symbol_pivot_counter',
            rpath=search_path,
            use=['kodocpp_includes'])
