#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='cxx',
            source='uncoded_symbols.cpp',
            target='../../uncoded_symbols',
            rpath=search_path,
            use=['kodocpp_includes'])
