#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='use_trace_layers.cpp',
            target='use_trace_layers',
            rpath=['.'],
            use=['kodocpp_includes'])
