#! /usr/bin/env python
# encoding: utf-8

# bld.stlib(
#     source=bld.path.ant_glob('**/*.cpp'),
#     target='cppkodo',
#     name='cppkodo_static',
#     export_includes='src',
#     use=['kodo_includes', 'boost_includes', 'fifi_includes',
#     'sak_includes', 'platform_includes'])

# if 'BUILD_CPPKODO_SHARED_LIBRARY' in bld.env:

bld.shlib(
    source=bld.path.ant_glob('**/*.cpp'),
    target='cppkodo',
    name='cppkodo_shared',
    install_path=None,
    export_includes='src',
    use=['kodo_includes', 'boost_includes', 'fifi_includes',
         'sak_includes', 'platform_includes'])
