#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='cxx',
            source='encode_decode_on_the_fly.cpp',
            target='../../encode_decode_on_the_fly',
            rpath=search_path,
            use=['kodocpp'])
