#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='encode_decode_on_the_fly.cpp',
            target='encode_decode_on_the_fly',
            use=['kodocpp_static_includes'])
