#! /usr/bin/env python
# encoding: utf-8

bld.shlib(
    features='cxx',
    source=bld.path.ant_glob('**/*.cpp'),
    target='kodocpp',
    name='kodocpp',
    install_path=None,
    export_includes='..',
    use=['kodo_includes', 'boost_includes', 'fifi_includes',
         'sak_includes', 'platform_includes'])
