#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='symbol_status_updater.cpp',
            target='symbol_status_updater',
            use=['kodocpp_static_includes'])
