#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='cxx',
            source='symbol_status_updater.cpp',
            target='symbol_status_updater',
            rpath=search_path,
            use=['kodocpp_includes'])
