#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='sliding_window.cpp',
            target='sliding_window',
            rpath=['.'],
            use=['kodocpp_includes'])