#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(features='cxx',
            source='switch_systematic_on_off.cpp',
            target='../../switch_systematic_on_off',
            rpath=search_path,
            use=['kodocpp'])
