#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='encode_decode_simple.cpp',
            target='encode_decode_simple',
            use=['kodocpp_static_includes'])
