#! /usr/bin/env python
# encoding: utf-8

static_libs = []

# The C++ standard library must be added on Linux and Android
if bld.get_mkspec_platform() in ['linux', 'android']:
    static_libs = ['stdc++']

bld.program(features='cxx',
            source='encode_decode_simple.cpp',
            target='encode_decode_simple',
            use=['kodo_includes', 'boost_includes', 'fifi_includes',
                 'sak_includes'])
